AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Innovator Island - Flow & Traffic Controller (ride queue times service).

Globals:
  Function:
    Handler: app.handler
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Environment:
      Variables:
        DDBtable: !Ref DDBtable


Resources:

  # Ride times are published to this topic
  FATcontroller:
    Type: AWS::SNS::Topic

  # Table to hold state between Lambda invocations

  DDBtable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ID
        Type: String
        
  # Function to simulate ride times and closures
  UpdateRides:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fatController/
      Timeout: 10
      Environment:
        Variables:
          TopicArn: !Ref FATcontroller      
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBtable  
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FATcontroller.TopicName                
      Events:
        UpdateRidesEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  # Lambda function for initializing DDB table content
  AppConfigurationLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: initDB/
      Timeout: 15
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBtable                 

  # Triggers Lambda function after stack creation to add rides to DDB
  DeploymentCustomResource:
    Type: Custom::AppConfiguration
    Properties:
      ServiceToken: !GetAtt AppConfigurationLambda.Arn

Outputs:
  RideUpdatesSNStopic:
      Description: "SNS topic to receive ride uptime updates"
      Value: !Ref FATcontroller
